CREATE TABLE `reply`(
`id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
`board_id` BIGINT(20) UNSIGNED NOT NULL,
`writer_account` VARCHAR(20) NOT NULL,
`nick_name` VARCHAR(50) NOT NULL,
`content` TEXT NOT NULL,
`deleted` BOOLEAN NOT NULL DEFAULT FALSE,
`updated_at` TIMESTAMP NOT NULL DEFAULT NOW() ON UPDATE NOW(),
`created_at` TIMESTAMP NOT NULL DEFAULT NOW(),
PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;
